### PR TITLE
Added fun commands

### PR DESCRIPTION
**Pull request by HPaulson**
Added 'coinflip' and 'dice' fun commands

### CODE REVIEW

**Comment by TannerReynolds** [comment]
on the flip cmd, you'll need to change that `var` declaration to a `let` declaration.

For the Dice cmd, the only thing that needs to change is the way the emoji is done. It should be 
```
msg.channel.createMessage(`${meteor.emojis.dice} You rolled a ${Math.floor(Math.random() * 6) + 1}`)
```
[meteor.js](https://github.com/TannerReynolds/Meteor/blob/master/app/meteor.js) has the definition for emojis on [Line 28](https://github.com/TannerReynolds/Meteor/blob/63f7ed0eb5649aa28ed087d1db69ed538cad7eac/app/meteor.js#L28)
And then for both you should be using semi-colons.

Once you make those changes we can then merge this commit! And I'll also add an eslint config to this as well so that styling information can be made available in the repository

**Comment by HPaulson** [comment]
All requested changed committed

**Comment by TannerReynolds** [comment]
Thank you!

**Comment by C0braD3v** [comment]
I'm assuming you'd like me to fix the emoji in fortune cookie? What would the correct emoji be?

**Pull request merged**
